apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
spec:
  containers:
  - name: demo-container
    image: busybox
    command: ["sh", "-c", "echo APP_ENV=$APP_ENV && echo DB_USER=$DB_USER && echo DB_PASSWORD=$DB_PASSWORD && sleep 3600"]
    envFrom:
    - configMapRef:
        name: {{ .Release.Name }}-config
    - secretRef:
        name: {{ .Release.Name }}-secret
